[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.backends._legacy:_Backend"
[project]
name = "timeutils"
version = "0.1.0"
[tool.setuptools.packages.find]
where = ["src"]